version: '3.3'


networks:
  network:
    # name: net

volumes:
  website:
    driver_opts:
      type: staticws
      device: /${HOME}/web
      o: bind
  database:
    driver_opts:
      type: none
      device: ${HOME}/db
      o: bind


# ! NGINX
services:
  nginx:
    depends_on:
      - wordpress
    container_name  : nginx
    image           : nginx:${TITLE}
    build           : requirements/nginx/
    ports           :
      - "443:443"
    volumes:
      - website:/var/www/wordpress
    networks:
      - network
    restart: always

# ! WordPress
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    image: wordpress:${TITLE}
    build:
      context: requirements/wordpress/
      args:
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - DB_HOST=mariadb:3306=value
    networks:
      - network
    environment:
      DOMAIN_NAME : ${DOMAIN_NAME}
      TITLE : ${TITLE}
      WP_ADMIN_USER : ${WP_ADMIN_USER}
      WP_ADMIN_PASS : ${WP_ADMIN_PASS}
      WP_ADMIN_MAIL : ${WP_ADMIN_MAIL}
      WP_USER : ${WP_USER}
      WP_PASS : ${WP_PASS}
    volumes:
      - website:/var/www/wordpress
    restart: always

# ! MARIADB
  mariadb:
    container_name: mariadb
    image: mariadb:${TITLE}
    build:
      context: requirements/mariadb/
      args:
      - TITLE=${TITLE}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_ROOT_PASS=${MYSQL_ROOT_PASS}
    networks:
      - network
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - TITLE=${TITLE}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_ROOT_PASS=${MYSQL_ROOT_PASS}
    restart: always
