FROM	alpine:3.15

RUN     apk update --no-cache && \
        apk add php php7-fpm php7-mysqli php7-json php7-phar\
        php7-iconv php7-mbstring mariadb-client redis
        # apk add --no-cache wordpress

# RUN
